### ISSUE TITLE
Populate Countries and State Migration Aborted

### ISSUE THREAD

**Issue by marz0** [piggybak/piggybak#89] opened 2016-01-23 19:19 UTC
I was having an issue while setting up the schema from a fresh app.

```
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.0/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
== 20160123032751 PopulateCountriesAndStates: migrating =======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `[]' for #<ISO3166::Country:0x007f85d4e2adb8>/Users/marcel/Desktop/RoR/piggy/db/migrate/20160123032751_populate_countries_and_states.piggybak.rb:14:in `block in up'
/Users/marcel/Desktop/RoR/piggy/db/migrate/20160123032751_populate_countries_and_states.piggybak.rb:13:in `each'
/Users/marcel/Desktop/RoR/piggy/db/migrate/20160123032751_populate_countries_and_states.piggybak.rb:13:in `up'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:598:in `exec_migration'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:578:in `block in migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:577:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:752:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/transactions.rb:208:in `transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:1038:in `ddl_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:953:in `block in migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:949:in `each'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:949:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:807:in `up'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:785:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `[]' for #<ISO3166::Country:0x007f85d4e2adb8>
/Users/marcel/Desktop/RoR/piggy/db/migrate/20160123032751_populate_countries_and_states.piggybak.rb:14:in `block in up'
/Users/marcel/Desktop/RoR/piggy/db/migrate/20160123032751_populate_countries_and_states.piggybak.rb:13:in `each'
/Users/marcel/Desktop/RoR/piggy/db/migrate/20160123032751_populate_countries_and_states.piggybak.rb:13:in `up'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:598:in `exec_migration'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:578:in `block in migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:577:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:752:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/transactions.rb:208:in `transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:1038:in `ddl_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:953:in `block in migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:949:in `each'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:949:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:807:in `up'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/migration.rb:785:in `migrate'
/Users/marcel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.0/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

I realized it was the PopulateCountriesAndStates migration so I had to mess with it to get it to work. This is the change I had to make to get it to run the migration.  The migrations run now, but I'm not sure if it's a complete fix:

```
    ISO3166::Country.all.each do |country_array|
      name = country_array.data["name"]
      abbr = country_array.data["alpha2"]
```

After looking at the admin dashboard and seeing the names of states and abbreviations being backwards, I rolled back the migrations and changed what the name and abbr are being set to.

```
      iso3166_country = ISO3166::Country.new(abbr)
      iso3166_country.states.each do |key, value|
        abbr = key
        name = value["name"]
        Piggybak::State.create! :name => name, :abbr => abbr, :country => country
```

**Comment by patricklewis** [comment] 2016-01-24 19:34
Duplicate of #84, a similar migration fix has been committed to the master branch.

**Closed by patricklewis** 2016-01-24 19:34 UTC
